### ISSUE TITLE
如何才能替换默认的繁体明月拼音

### ISSUE THREAD

**Issue by AndreaFrederica** [sdadonkey/rime-english#7]
原先是想更改中文的输出为简体，但是按照GitHub上的范例更改并没有用
而后想替换明月拼音为另一原生简体方案来实现这个效果
但是直接更改依赖名和下面的函数名（？）会导致引擎崩溃
而单独更改辞典则会导致它失效？
故来询问正确的使用方法

**Comment by yu-soong** [comment]
在 `switches`: 下面添加   
```
- name: simplification
    states: [ 简, 繁 ]
    reset: 0
```

  `filters`: 下面添加
`    - simplifier@simplification`

应该就可以了

**Comment by AndreaFrederica** [comment]
感谢回复了 这个方法能用 谢谢了

**Comment by AndreaFrederica** [comment]
感谢回复了 这个方法能用 谢谢了

**Comment by dongyuwei** [comment]
> 在 `switches`: 下面添加

请问是添加到  english.schema.yaml 中还是别的配置文件中？我试了在  english.schema.yaml 中修改貌似没有效果，按shift切换后还是繁体输出。

**Comment by dongyuwei** [comment]
okay, 我折腾成功了。在 english.schema.yaml 中修改
```yaml
switches:
  - name: simplification
    states: [漢字, 汉字]
    reset: 1 #加这个配置按shift出简体中文

filters:
    - simplifier
    - simplifier@simplification  #加这个配置按shift出简体中文
    - uniquifier
    # 以下兩個二選一
    - lua_filter@english_filter # 速度快，但詞議相同拼寫相近單詞可能會被Rime略去
    #- lua_filter@english_filter0           # 速度稍慢，但詞典中允許出現拼寫或詞義相同單詞
```
